"""Every number the plan v3 paper extension may print, read from the records with its provenance and status.

    python -m tether.analysis.v3.paper_evidence        # renders reports/v3/paper_evidence.md

No number here is typed into this module: each is read from a record under ``records/v3/`` (or computed from
the plant constants by ``tether/theory/transmission.py``, which is itself pinned in the declarations), and each
row carries the record and key it came from.  The STATUS column is the discipline this campaign runs on:

  MEASURED     a scored result of a pre-registered test;
  FORECAST     committed in ``cascade_predictions.json`` before any run, and never a result;
  SENSITIVITY  post hoc, declared in a dated addendum, reported beside a verdict and never scored;
  DERIVED      arithmetic on the declared plant constants.

The last section lists the claims the extension must NOT make, taken from the gate records and the audit
rounds, so that a drafting pass cannot quietly promote a failed test into a result.
"""

from __future__ import annotations

import json

from tether.campaign.common import REPORTS, sha256_file, write_bytes
from tether.campaign.v3 import campaign
from tether.theory import transmission as TR

OUT = REPORTS / "v3" / "paper_evidence.md"
CAL = "T600_k500_I0.5"
RECORDS = ("cascade_declarations.json", "cascade_predictions.json", "wp1_results.json", "wp1_sensitivity.json",
           "wp2_results.json", "wp3_results.json", "gate_wp1.json", "gate_wp2.json", "gate_wp3.json",
           "cascade_addendum_1.json", "cascade_addendum_2.json", "cascade_addendum_3.json")


def _load(name: str):
    path = campaign.RECORD_DIR / name
    return json.loads(path.read_text()) if path.exists() else None


def build() -> str:
    out: list[str] = []
    add = out.append
    w1, w2, w3 = _load("wp1_results.json"), _load("wp2_results.json"), _load("wp3_results.json")
    s1, pred = _load("wp1_sensitivity.json"), _load("cascade_predictions.json")
    g3 = _load("gate_wp3.json")
    add("# Evidence table for the paper extension")
    add("")
    add("Generated by `python -m tether.analysis.v3.paper_evidence` (`make v3-evidence`) from the records in")
    add("`records/v3/`; no number is typed into the generator. **STATUS**: MEASURED (a scored result), FORECAST")
    add("(committed before the runs, never a result), SENSITIVITY (post hoc, declared in a dated addendum, never")
    add("scored), DERIVED (arithmetic on the declared plant constants).")
    add("")

    def table(header: list[str]) -> None:
        add("| " + " | ".join(header) + " |")
        add("|" + "|".join("---" for _ in header) + "|")

    def row(*cells: str) -> None:
        add("| " + " | ".join(str(c) for c in cells) + " |")

    # ---------------------------------------------------------------- the law itself
    add("## The transmission law, derived")
    add("")
    table(["Quantity", "Value", "Status", "Record or code"])
    f = TR.frequencies()
    row("closed-form ratio $2k/(m_L\\omega_L\\omega_e)$", f"{TR.closed_form_ratio():.3f}", "DERIVED", "`theory/transmission.py::closed_form_ratio`")
    row("$\\omega_e$, $\\omega_L$, $\\varepsilon = \\omega_L/\\omega_e$", f"{f['omega_e']:.2f}, {f['omega_L']:.2f} rad/s, {f['epsilon']:.3f}", "DERIVED", "`::frequencies`")
    row("engagement period $P = 2\\pi\\sqrt{\\mu/k}$", f"{f['engagement_period']:.3f} s", "DERIVED", "`::frequencies`")
    if pred:
        rng = sorted(c["transmission"]["band_statistic_median_offdiag"] for c in pred["cells"].values())
        row("exact linear response, calibration cell", f"{pred['cells'][CAL]['transmission']['band_statistic_median_offdiag']:.3f}", "FORECAST", f"`cascade_predictions.json cells.{CAL}`")
        row("exact linear response, across the cells", f"{rng[0]:.3f}-{rng[-1]:.3f}", "FORECAST", "`cascade_predictions.json`")
    add("")

    # ---------------------------------------------------------------- WP1
    add("## WP1 &mdash; the transmission as pre-registered")
    add("")
    if not w1:
        add("_not yet run_"); add("")
    else:
        t = w1["tests"]
        table(["Test", "Verdict", "Numbers", "Record"])
        row("T1.0 reused cells reproduce the v1 marks", f"**{t['T1.0']['verdict']}**",
            f"{t['T1.0']['checked_runs']} runs, {t['T1.0']['failed_runs']} failed ({t['T1.0'].get('empty_vs_empty_runs', 0)} vacuous)", "`tests.T1.0`")
        row("T1.1 the paper's band $[0.2, 0.9]$", f"**{t['T1.1']['verdict']}**",
            f"{t['T1.1']['passing_cells']}/{t['T1.1']['scored_cells']} cells inside (the committed forecast was FAIL)", "`tests.T1.1`")
        row("T1.2 pair pattern against the exact response", f"**{t['T1.2']['verdict']}**",
            f"{t['T1.2']['passing_cells']}/{t['T1.2']['scored_cells']} cells with $\\rho_S \\ge 0.7$", "`tests.T1.2`")
        row("T1.3 small-peak accuracy, $x \\le 2.3$", f"**{t['T1.3']['verdict']}**",
            f"{t['T1.3']['passing_cells']}/{t['T1.3']['scored_cells']} cells within a factor $1.5$", "`tests.T1.3`")
        t14 = t["T1.4"]
        row("T1.4 stiffness", f"**{t14['verdict']}**",
            f"$\\Delta_\\text{{meas}} = {t14['delta_measured']:+.3f}$ $[{t14['ci95'][0]:+.3f}, {t14['ci95'][1]:+.3f}]$ against "
            f"$\\Delta_\\text{{exact}} = {t14['delta_exact']:+.3f}$ and $0$ for the closed form", "`tests.T1.4`")
        add("")
        table(["Quantity", "Value", "Status", "Record and key"])
        cal = w1["cells"][CAL]
        lo = sorted(c["T1.1"]["median_drop_norm"] for c in w1["cells"].values())
        dg = sorted(c["sensitivities"]["design_geometry_median"] for c in w1["cells"].values())
        gp = sorted(c["sensitivities"]["share_rows_measured_factor_nonpositive"] for c in w1["cells"].values())
        row("declared normalised drop, per cell", f"{lo[0]:.3f}-{lo[-1]:.3f} (calibration {cal['T1.1']['median_drop_norm']:.3f} $[{cal['T1.1']['ci95'][0]:.3f}, {cal['T1.1']['ci95'][1]:.3f}]$)",
            "MEASURED", "`cells[*].T1.1`")
        row("like-for-like reading (design-geometry normaliser)", f"{dg[0]:.3f}-{dg[-1]:.3f} (calibration {cal['sensitivities']['design_geometry_median']:.3f} against the forecast {cal['T1.1']['committed_prediction']:.3f})",
            "SENSITIVITY", "`cells[*].sensitivities.design_geometry_median` (audit round 1, M1)")
        row("rows whose measured geometry factor is $\\le 0$", f"{100 * gp[0]:.0f}-{100 * gp[-1]:.0f} %", "MEASURED", "`cells[*].sensitivities`")
        add("")

    # ---------------------------------------------------------------- addendum 2
    add("## Addendum 2 &mdash; the transmission measured by intervention (post hoc, never scored)")
    add("")
    if not s1:
        add("_not yet run_"); add("")
    else:
        p = s1["pooled"]
        table(["Quantity", "Value", "Status", "Record and key"])
        row("declared window-drop statistic, pooled", f"{p['median_drop']:.3f}", "SENSITIVITY", "`wp1_sensitivity.json pooled.median_drop`")
        row("its no-snap floor (the same window, time-shifted)", f"{p['median_null']:.3f}", "SENSITIVITY", "`pooled.median_null`")
        row("interventional swing (counterfactual $-$ factual)", f"{p['median_swing']:.3f}", "SENSITIVITY", "`pooled.median_swing`")
        row("interventional swing / exact response", f"{p['median_swing_over_R']:.3f}", "SENSITIVITY", "`pooled.median_swing_over_R`")
        row("behind those numbers", f"{p['rows']} rows, {s1['compute']['runs']} runs, {s1['compute']['core_hours']:.1f} core-hours", "SENSITIVITY", "`compute`")
        for name, c in s1["cells"].items():
            if c["swing_pairs"]["pairs"]:
                row(f"pair pattern $\\rho_S$ against $R$, `{name}`",
                    f"{c['swing_pairs']['spearman_vs_R']:.2f} (the declared drop statistic gives {c['drop_pairs']['spearman_vs_R']:.2f})",
                    "SENSITIVITY", f"`cells.{name}.swing_pairs`")
        for name in ("T600_k500_I0.5_kx0.25", CAL, "T600_k500_I0.5_kx4"):
            c = s1["cells"].get(name)
            if c and c["rows"]:
                row(f"lag of the swing extremum, `{name}`", f"{1e3 * c['median_swing_lag_s']:.0f} ms", "SENSITIVITY", f"`cells.{name}.median_swing_lag_s`")
        add("")

    # ---------------------------------------------------------------- WP2
    add("## WP2 &mdash; the cascade as a branching process")
    add("")
    if not w2:
        add("_not yet run_"); add("")
    else:
        t = w2["tests"]
        table(["Test", "Verdict", "Numbers", "Record"])
        for tid, what in (("T2.1", "offspring curve monotone and vanishing below $T_0$"), ("T2.2", "transfer of the isotonic $\\hat m_x$"),
                          ("T2.3", "intervention validation"), ("T2.4", "causal against observational"), ("T2.5", "parameter-free kernel")):
            x = t[tid]
            n = f"{x['passing_cells']}/{x['scored_cells']} cells" if "scored_cells" in x else x.get("reason", "")
            row(f"{tid} {what}", f"**{x['verdict']}**", n, f"`tests.{tid}`")
        add("")
        v = t["T2.3"]
        table(["Quantity", "Value", "Status", "Record and key"])
        row("T2.3 residuals, all sampled parents",
            f"$n = {v['n']}$; $|\\Delta t|$ max {1e3 * v['abs_dt_s']['max']:.2f} ms (declared 5); $|\\Delta v|$ p95 {v['abs_dv_m_s']['p95']:.4f} m/s (declared 0.01); "
            f"peak p95 {100 * v['T_peak_relative_error']['p95_abs']:.2f} % (declared 2); onset sets {100 * v['onset_set_reproduced_share']:.2f} % (declared 95)",
            "MEASURED", "`tests.T2.3`")
        if "sensitivity_without_kx4" in v:
            row("T2.3 without the $k\\times4$ cell", f"onset sets {100 * v['sensitivity_without_kx4']['onset_set_reproduced_share']:.2f} %", "SENSITIVITY", "`tests.T2.3.sensitivity_without_kx4`")
        kp = w2["kernel_path"]["tested"]
        row("kernel path (the declared rule)",
            "; ".join(f"{k} {kp[k]['passing_cells']}/{kp[k]['scored_cells']} {kp[k]['verdict']}" for k in ("R", "R_hat", "empirical") if k in kp)
            + f"; chosen **{w2['K_path_chosen']}**", "MEASURED", "`kernel_path`")
        tt = [c["T2.5"].get("sensitivity_taut_neighbour_target") for c in w2["cells"].values()]
        tt = [x for x in tt if x]
        if tt:
            row("mechanistic kernel against the count it models",
                f"pooled {sum(x['predicted'] for x in tt) / sum(x['target'] for x in tt):.2f}; {sum(bool(x['in_band']) for x in tt)}/{len(tt)} cells within a factor 1.5",
                "SENSITIVITY", "`cells[*].T2.5.sensitivity_taut_neighbour_target` (audit round 2, M3)")
        iv = [c["intervention"] for c in w2["cells"].values()]
        if "net_causal" in iv[0]:
            row("causal offspring on the sampled parents",
                f"clipped {sum(x['causal'] for x in iv):.0f}, signed net {sum(x['net_causal'] for x in iv):.0f}, prevented {sum(x['prevented_onsets'] for x in iv):.0f}, "
                f"observational {sum(x['measured_cross_sampled'] for x in iv):.0f}", "MEASURED", "`cells[*].intervention` (audit round 2, M1)")
        add("")

    # ---------------------------------------------------------------- WP3
    add("## WP3 &mdash; criticality")
    add("")
    if not w3:
        add("_not yet run_"); add("")
    else:
        gated = g3 is not None
        add(f"**{'Gated' if gated else 'NOT YET GATED: no number in this section may be printed'}** "
            f"({'`gate_wp3.json` ' + g3['verdict'] if gated else 'audit round 3 open'}).")
        add("")
        t = w3["tests"]
        table(["Test", "Verdict", "Numbers", "Record"])
        for tid, what in (("T3.1", "cluster-corrected rate law"), ("T3.2", "extremal index"), ("T3.3", "primary rate against Rice"),
                          ("T3.5", "cluster-size law")):
            x = t[tid]
            n = f"{x['passing_cells']}/{x['scored_cells']} cells" if "scored_cells" in x else ""
            row(f"{tid} {what}", f"**{x['verdict']}**", n, f"`tests.{tid}`")
        t34 = t["T3.4"]
        row("T3.4 the sweep", f"**branch {t34['branch']}**",
            f"highest operable `{t34['highest_operable']}`, $\\rho = {t34['rho']:.3f}$, margin {t34['margin']:.3f}", "`tests.T3.4`")
        add("")
        table(["Intensity", "$\\rho$", "closures / runs", "operable"])
        for v in sorted(t34["table"].values(), key=lambda v: v["intensity"]):
            row(f"{v['intensity']:g}", f"{v['rho']:.2f}", f"{v['closures']}/22", str(v["operable"]))
        add("")

    # ---------------------------------------------------------------- provenance and prohibitions
    add("## Provenance")
    add("")
    for name in RECORDS:
        path = campaign.RECORD_DIR / name
        add(f"- `records/v3/{name}` &mdash; {'`' + sha256_file(path)[:16] + '...`' if path.exists() else '_absent_'}")
    add("")
    add("## Claims the extension must not make")
    add("")
    add("Each is a test that failed, or an estimator declared after its verdict was known; the gate records and")
    add("`reports/v3/corrections_log.md` carry the reasoning.")
    add("")
    if w2:
        add(f"- Not \"the parameter-free kernel predicts the offspring\": **T2.5 FAILED** "
            f"({w2['tests']['T2.5']['passing_cells']}/{w2['tests']['T2.5']['scored_cells']} cells) against its declared target.")
        add(f"- Not \"causal attribution is validated\": **T2.3 FAILED** "
            f"({100 * w2['tests']['T2.3']['onset_set_reproduced_share']:.2f} % against the declared 95 %), so T2.4 is UNSCORED and the")
        add("  declared branch reports the causal counts as untrusted.")
    if w1:
        add("- Not \"the pair pattern of the exact response is confirmed\": **T1.2 FAILED** on the pre-registered")
        add("  statistic; the pattern appears only in the post-hoc interventional estimator of addendum 2.")
    add("- Not \"we measured 0.95 of the exact response\" without the words *post hoc*: that estimator was declared")
    add("  in addendum 2, after the WP1 verdicts were known.")
    add("- Not any WP3 number at all until `records/v3/gate_wp3.json` exists.")
    add("")
    return "\n".join(out) + "\n"


def main() -> None:
    print(write_bytes(OUT, build().encode()), OUT)


if __name__ == "__main__":
    main()
